config/routes.rb
Zientia::Application.routes.draw do

  get "current/index"

  get "dashboard/index"

  get "usuario/logar"

  match 'current' => 'current#index'

  devise_for :users

  get "intro/index"

  devise_scope :user do
  
  get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  
  end

 
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'intro#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  # validações
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/current_controller.rb
class CurrentController < ApplicationController
  def index
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_filter :authenticate_user!

  def index
  
  end

end

app/controllers/intro_controller.rb
class IntroController < ApplicationController
  def index

  	if user_signed_in?
  		# caso o aluno esteja logado, redireciona-lo para o dashboard da app
  		redirect_to :controller=>'dashboard', :action => 'index'
  	else

  	end # fim do if usuario logado

  end # fim da action index


end #final do controller

app/controllers/usuario_controller.rb
class UsuarioController < ApplicationController
  def logar
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/current_helper.rb
module CurrentHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/intro_helper.rb
module IntroHelper
end

app/helpers/usuario_helper.rb
module UsuarioHelper
end

app/views/current/index.html.erb
<h1>Zientia Educacional</h1>
<p>Segue abaixo alguns anexos da proposta submetida ao programa Startup Brasil.</p>

<br>

<h4>Identidade Visual</h4>

<p><%= image_tag('/anexo/znt1.jpg') %></p>

<br>

<h4>Identidade Visual (Branco) </h4>

<p><%= image_tag('/anexo/znt3.jpg', :style => 'width:1025px; height:749px;') %></p>
<br>

<h4>Icone Aplicação iPad</h4>

<p><%= image_tag('/anexo/icon_no_retina.png') %></p>
<br>

<h4>SplashScreen iPad</h4>

<p><%= image_tag('/anexo/splashscreen_ipad_zientia.png') %></p>

<br>

<h4>Tela Login iPad</h4>

<p><%= image_tag('/anexo/login_ipad_zientia.png') %></p>

<br>

<h4>Tela Login Web</h4>

<p><%= image_tag('/anexo/zientia_web_login.png') %></p>

<br>

<h4>Escopo Aluno logado plataforma web</h4>

<p><%= image_tag('/anexo/zientia_web_logado.png') %></p>

app/views/dashboard/index.html.erb
<div id="wrapper">
  
  <div id="header">
    <h1><%= link_to image_tag('/images/logoz.png'), root_path %></h1>    
    
    <a href="javascript:;" id="reveal-nav">
      <span class="reveal-bar"></span>
      <span class="reveal-bar"></span>
      <span class="reveal-bar"></span>
    </a>
  </div> <!-- #header -->
  
  <div id="search">
    <form>
      <input type="text" name="search" placeholder="Buscar..." id="searchField" />
    </form>   
  </div> <!-- #search -->
  
  <div id="sidebar">    
    
  	<%= render 'shared/menu_dashboard' %>
        
  </div> <!-- #sidebar -->
  
  <div id="content">    
    
    <div id="contentHeader">
      <h1>Bem vindo <%= current_user.email.split('@').first %></h1>
    </div> <!-- #contentHeader -->  
    
    <div class="container">
      
    <!-- trazer o yield do rails aqui  -->
      
    </div> <!-- .container -->
    
  </div> <!-- #content -->
  
  <div id="topNav">
     <ul>
      <li>
        <a href="#menuProfile" class="menu"><%= current_user.email %></a>
        
        <div id="menuProfile" class="menu-container menu-dropdown">
          <div class="menu-content">
            <ul class="">
              <li><a href="javascript:;">Perfil</a></li>
              <li><a href="javascript:;">Desempenho</a></li>
              <li><a href="javascript:;">Faltas</a></li>
            </ul>
          </div>
        </div>
      </li>
      <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
     </ul>
  </div> <!-- #topNav -->
  
  <div id="quickNav">
    <ul>
      <li class="quickNavMail">
        <a href="#menuAmpersand" class="menu"><span class="icon-book"></span></a>   
        
        <span class="alert">2</span>    

        <div id="menuAmpersand" class="menu-container quickNavConfirm">
          <div class="menu-content cf">             
            
            <div class="qnc qnc_confirm">
              
              <h3>Atividades</h3>
          
              <div class="qnc_item">
                <div class="qnc_content">
                  <span class="qnc_title">Atividade 1</span>
                  <span class="qnc_preview">O  professor (x) adicionou você a uma atividade</span>
                  <span class="qnc_time">1 min atrás</span>
                </div> <!-- .qnc_content -->
                
                <div class="qnc_actions">           
                  <button class="btn btn-primary btn-small">Fazer</button>
                  <button class="btn btn-quaternary btn-small">Agora não</button>
                </div>
              </div>

              <div class="qnc_item">
                <div class="qnc_content">
                  <span class="qnc_title">Atividade 2</span>
                  <span class="qnc_preview">Atividade de Portugês para entregar hoje.</span>
                  <span class="qnc_time">3 horas atrás</span>
                </div> <!-- .qnc_content -->
                
                <div class="qnc_actions">           
                  <button class="btn btn-primary btn-small">Fazer</button>
                  <button class="btn btn-quaternary btn-small">Agora não</button>
                </div>
              </div>
              
              
              
              <a href="javascript:;" class="qnc_more">Visualizar atividades</a>
                              
            </div> <!-- .qnc -->  
          </div>
        </div>
      </li>
      <li class="quickNavNotification">
        <a href="#menuPie" class="menu"><span class="icon-chat"></span></a>
         <span class="alert">2</span> 
        <div id="menuPie" class="menu-container">
          <div class="menu-content cf">         
            
            <div class="qnc">
              
              <h3>Notificações</h3>
          
              <a href="javascript:;" class="qnc_item">
                <div class="qnc_content">
                  <span class="qnc_title">Aula apoio (Geografia)</span>
                  <span class="qnc_preview">Aula de apoio ministrada pelo professor (X) as 16:30</span>
                  <span class="qnc_time">3 horas atrás</span>
                </div> <!-- .qnc_content -->
              </a>
              
              <a href="javascript:;" class="qnc_item">
                <div class="qnc_content">
                  <span class="qnc_title">Parabéns!!!</span>
                  <span class="qnc_preview">Parabéns, você atingiu a nota Dez em Portugês.</span>
                  <span class="qnc_time">2 dias atrás</span>
                </div> <!-- .qnc_content -->
              </a>
              
              <a href="javascript:;" class="qnc_more">Visualizar todas</a>
              
            </div> <!-- .qnc -->
          </div>
        </div>        
      </li>
    </ul>   
  </div> <!-- .quickNav -->
</div> <!-- #wrapper -->

app/views/intro/index.html.erb
           
           <div class="intro_topo">

           	<div class="entrar">
           	<%= link_to "Usar", new_user_session_path, :style => "color:white; font-size:20px; text-decoration:underline;" %>
           	</div>           	

           	<div style="margin-top:60px; margin-left:-50px;">

           		<center><%= link_to image_tag('/images/logo_zientia.png'), root_path %></center>

           	</div>


           </div>
           <center>
           <div class="presentation">
           	
           	<div style="float:left; margin-left:20px; margin-top:15px; width:72px;">
           		<%= image_tag('/images/books.png') %>

           	</div>
           	
           	<h2 style="color:#003006; margin-top:25px; float:left; margin-left:70px; text-decoration:underline;">Resenha</h2>
           	<p style="text-align:justify; float:left; margin-top:30px; padding:10px; line-height:180%; font-weight:bold; text-indent: 1.5em;"> Plataforma de entrega de conteúdo didático digital, no qual o aluno e o professor, dentro de sala de aula, poderão criar grupos de troca de conhecimento, realizar leituras com conteúdos digitais (e-books), fazer aulas com Realidade Aumentada ou via Aplicações Mobile, trocar arquivos na nuvem, acompanhar um feed de notícias criado na sala de aula e além disso trocar mensagens entre si. </p>
           </div>
           </center>
           <br><br>
           <center><p style="color:#003006; left:45%; position:fixed; bottom:0; margin-top:0px;">2013 Zientia</p></center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zientia Educacional</title>

   <!-- JQUERY -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/jquery-1.7.1.min.js"><\/script>')</script>
 
    <!-- TWITTER BOOTSTRAP CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet" type="text/css" />
 
    <!-- TWITTER BOOTSTRAP JS -->
    <script src="/js/bootstrap.min.js"></script>




  <%= stylesheet_link_tag    "/css/bootstrap", :media => "all" %>
  <%= stylesheet_link_tag    "/css/usuario" %>
  <%= javascript_include_tag "/js/bootstrap" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/current.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zientia Educacional - Anexos Startup Brasil</title>
</head>
<body style="background:#dfdfdf;">

<%= yield %>

</body>
</html>

app/views/layouts/dashboard.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>

  <title>Zientia Educacional | Dashboard</title>

  <meta charset="utf-8" />
  <meta name="description" content="" />
  <meta name="author" content="" />   
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
  <%= stylesheet_link_tag    "/stylesheets/all", :media => "all" %>
  <%= javascript_include_tag "/javascripts/all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
  <!--[if gte IE 9]>
  <link rel="stylesheet" href="stylesheets/ie9.css" type="text/css" />
  <![endif]-->
  
  <!--[if gte IE 8]>
  <link rel="stylesheet" href="stylesheets/ie8.css" type="text/css" />
  <![endif]-->
  
</head>

<body>

<%= yield %>

<!-- Footer -->
<div id="footer">
  Copyright &copy; 2013, Zientia.
</div>

<!-- chamando arquivos javascripts -->

</body>
</html>

app/views/layouts/intro.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zientia Educacional</title>

   <!-- JQUERY -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/jquery-1.7.1.min.js"><\/script>')</script>
 
    <!-- TWITTER BOOTSTRAP CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet" type="text/css" />
 
    <!-- TWITTER BOOTSTRAP JS -->
    <script src="/js/bootstrap.min.js"></script>




  <%= stylesheet_link_tag    "/css/bootstrap", :media => "all" %>
  <%= stylesheet_link_tag    "/css/application" %>
  <%= javascript_include_tag "/js/bootstrap" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/usuario.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zientia Educacional</title>

   <!-- JQUERY -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/jquery-1.7.1.min.js"><\/script>')</script>
 
    <!-- TWITTER BOOTSTRAP CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet" type="text/css" />
 
    <!-- TWITTER BOOTSTRAP JS -->
    <script src="/js/bootstrap.min.js"></script>




  <%= stylesheet_link_tag    "/css/bootstrap", :media => "all" %>
  <%= stylesheet_link_tag    "/css/usuario" %>
  <%= javascript_include_tag "/js/bootstrap" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_menu_dashboard.html.erb
    <ul id="mainNav">     
      <li id="navDashboard" class="nav active">
        <span class="icon-home"></span>
        <a href="dashboard.html">Dashboard</a>        
      </li>

      <li id="navType" class="nav">
        <span class="icon-rss-alt"></span>
        <a href="typography.html">Feed</a>  
      </li>
      
      <li id="navGrid" class="nav">
        <span class="icon-book"></span>
        <a href="grids.html">Biblioteca</a>  
      </li>
      
      <li id="navTables" class="nav">
        <span class="icon-cloud"></span>
        <a href="tables.html">Cloud</a>  
      </li>
      
      <li id="navButtons" class="nav">
        <span class="icon-at"></span>
        <a href="buttons.html">Aplicativos</a>  
      </li>
      
      <li id="navInterface" class="nav">
        <span class="icon-hash"></span>
        <a href="interface.html">English Content</a> 
      </li>
    
    </ul>

app/views/usuario/logar.html.erb
<h2>Sign in</h2>

<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <% if devise_mapping.rememberable? -%>
    <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
  <% end -%>

  <div><%= f.submit "Sign in" %></div>
<% end %>

<%= render "devise/shared/links" %>